### ISSUE TITLE
Create Simple WebApp

### ISSUE THREAD

**Issue by thealphadollar** [CodeStash-KGP/set_proxy#18]
Create a simple web app using python's flask or any other tool which can be easily hosted on heroku. 

The website should contain [atleast] the following:

- Link to download the script and information about it.
- Written details about what needs to be set apart from the script.
- Link to contribute to github for the project.

References that can be useful:
https://medium.com/the-andela-way/deploying-a-python-flask-app-to-heroku-41250bda27d0

**Comment by mukul-mehta** [comment]
Hi,
I would like to work on this issue.

**Comment by thealphadollar** [comment]
I don't think so; please tell you operating system.

**Comment by mukul-mehta** [comment]
elementary is based on Ubuntu. 
Once I'm done with the flask application, do you want me to deploy on Heroku as well?

**Comment by thealphadollar** [comment]
No, that I'll do.

**Comment by thealphadollar** [comment]
Also, it is not necessary that a distribution based on Ubuntu works the
same as Ubuntu and so does all it's system commands.

**Comment by mukul-mehta** [comment]
Oh, ok. Thanks! I'll create a pull request soon!
