### ISSUE TITLE
Add Docker Proxy Instructions/Settings

### ISSUE THREAD

**Issue by thealphadollar** [CodeStash-KGP/set_proxy#19]
Add proxy instructions regarding docker; this needs use of services as well. Below are the detailed instructions:

https://stackoverflow.com/questions/23111631/cannot-download-docker-images-behind-a-proxy

**Comment by baymac** [comment]
Reminding you to close this issue @thealphadollar

**Comment by thealphadollar** [comment]
Fixed via #23
