### ISSUE TITLE
Embed Google Analytics

### ISSUE THREAD

**Issue by thealphadollar** [CodeStash-KGP/set_proxy#25]
Since now we have a website, we can track the usage simply by embedding Google Analytics script into it.

The student should embed a demo key with the code and I'll later add mine.

References: https://developers.google.com/analytics/devguides/collection/analyticsjs/

**Comment by thealphadollar** [comment]
@mukul-kgp You might want to do this.

**Comment by mukul-mehta** [comment]
Sure, I'll look into it in a few days. Right now I'm out of town on vacation with no laptop access!

**Comment by thealphadollar** [comment]
Fixed.
