### ISSUE TITLE
Instructions in the webapp are not in sync with the demo and do not work

### ISSUE THREAD

**Issue by Ayushk4** [CodeStash-KGP/set_proxy#31]
The file being downloaded from the heroku-app is set_proxy.sh
The instructions in the site are suggested for running the file named as set_proxy-master.sh
The demo screen shot updated isn't in sync with the instructions displayed.
Refer : https://i.imgur.com/6E5ANln.png 

It is a simple task that can be solved by editting set_proxy/templates/index.html.

**Comment by thealphadollar** [comment]
Is the issue still there? @Ayushk4

**Comment by Ayushk4** [comment]
Yep.

**Comment by Ayushk4** [comment]
Only three words need to be changed to fix this.

**Comment by thealphadollar** [comment]
fixed.
