### ISSUE TITLE
The link to metakgp opens codestash FB page

### ISSUE THREAD

**Issue by xypnox** [CodeStash-KGP/set_proxy#39]
# Expected Behavior

It should open the MetaKGP FB page

# Current Behavior

It opens the Codestash FB page

## Steps to Reproduce

1. Power on the PC
2. Login
3. Open the Browser
4. Open the website
5. Click on the link labled "MetaKGP"

**Comment by mukul-mehta** [comment]
@xypnox this is excessively comprehensive :P

**Comment by thealphadollar** [comment]
fixed via 973bcdedc97a681ea7277830b660b7e58dcb5bed
