### ISSUE TITLE
unset doesn't work

### ISSUE THREAD

**Issue by arnab39** [CodeStash-KGP/set_proxy#7]
Whenever I try to unset it it gives this:
sed: -e expression #1, char 0: no previous regular expression
And even after restart I see the same proxy setting in all the files which I have to manually change.

**Comment by thealphadollar** [comment]
Hey @arnab39 , thanks for bringing the issue to light. I'll try to fix it as soon as possible.

**Comment by thealphadollar** [comment]
@arnab39  Fixed.
